json.id resource.id
json.title resource.title
json.source resource.source
json.value resource.value
json.probability resource.probability
json.status resource.status
json.position resource.position
json.expected_close_date resource.expected_close_date
json.closed_at resource.closed_at&.to_i
json.stage_changed_at resource.stage_changed_at&.to_i
json.last_activity_at resource.last_activity_at&.to_i
json.notes resource.notes
json.custom_attributes resource.custom_attributes
json.additional_attributes resource.additional_attributes
json.contact_id resource.contact_id
json.sales_pipeline_id resource.sales_pipeline_id
json.sales_stage_id resource.sales_stage_id
json.assignee_id resource.assignee_id
json.label_list resource.label_list
json.created_at resource.created_at.to_i
json.updated_at resource.updated_at.to_i
