json.id resource.id
json.business_type resource.business_type
json.neighborhood resource.neighborhood
json.city resource.city
json.state resource.state
json.desired_count resource.desired_count
json.min_rating resource.min_rating
json.min_reviews resource.min_reviews
json.require_phone resource.require_phone
json.require_website resource.require_website
json.exclude_keywords resource.exclude_keywords
json.active resource.active
json.scheduled_hour resource.scheduled_hour
json.scheduled_minute resource.scheduled_minute
json.auto_contact_enabled resource.auto_contact_enabled
json.contact_tag resource.contact_tag
json.last_run_at resource.last_run_at&.to_i
json.created_at resource.created_at.to_i
