require 'rails_helper'

RSpec.describe Whatsapp::Connector::Consumer::ShardWorker, :redis_streams do
  subject(:worker) { described_class.new(0, 'consumer-1', lease) }

  let(:prefix) { "watest#{SecureRandom.hex(4)}:" }
  let(:redis) { Redis.new(Redis::Config.app) }
  # A real lease, taken before the worker reads anything: freshness is what fences a
  # dispatch, so a stub here would be testing the worker against a rule it does not have.
  let(:lease) do
    Whatsapp::Connector::Consumer::ShardLease.new(redis, 'consumer-1').tap { |held| held.take(0) }
  end
  let(:channel) do
    create(:channel_whatsapp, provider: 'native', validate_provider_config: false, sync_templates: false)
  end
  # Generated by the channel and never dictated: it is the address the connector holds the
  # session under, so nothing outside the model gets to choose it.
  let(:session_id) { channel.provider_config['session_id'] }
  let(:inbox) { channel.inbox }
  let(:stream) { "#{prefix}events:0" }
  let(:frame) do
    {
      'v' => '1', 'id' => 'evt-1', 'type' => 'message.received', 'sid' => session_id,
      'epoch' => '1', 'seq' => '1', 'ts' => '1755440000123',
      'payload' => {
        message: {
          id: '3EB0AAAA0001', chat: { kind: 'phone', id: '5541999990000' },
          sender: { phone: '5541999990000', lid: '182736451928374', push_name: 'Ana Souza' },
          from_me: false, timestamp: 1_755_440_000_123, content: { type: 'text', body: 'oi' }
        }
      }.to_json
    }
  end

  around do |example|
    with_modified_env(WHATSAPP_CONNECTOR_REDIS_PREFIX: prefix) { example.run }
    keys = redis.keys("#{prefix}*")
    redis.del(*keys) if keys.any?
  end

  before { channel }

  it 'dispatches what it reads and acknowledges it' do
    redis.xadd(stream, frame)

    expect(worker.poll).to eq(1)

    expect(inbox.messages.pluck(:source_id)).to eq(['3EB0AAAA0001'])
    expect(redis.xpending(stream, described_class::Consumer::GROUP)['size']).to eq(0)
    expect(redis.get("#{prefix}cursor:#{session_id}")).to eq('1:1')
  end

  it 'skips an event whose session no inbox claims' do
    redis.xadd(stream, frame.merge('sid' => 'a-session-nobody-owns'))

    expect(worker.poll).to eq(1)
    expect(inbox.messages).to be_empty
  end

  it 'drops a redelivery it has already processed' do
    redis.xadd(stream, frame)
    worker.poll
    inbox.messages.destroy_all

    redis.xadd(stream, frame)
    worker.poll

    # The cursor, not the message row, is what makes this a no-op.
    expect(inbox.messages).to be_empty
  end

  it 'still processes an event from a newer epoch' do
    redis.xadd(stream, frame)
    worker.poll

    redis.xadd(stream, frame.merge('id' => 'evt-2', 'epoch' => '2', 'seq' => '1',
                                   'payload' => JSON.parse(frame['payload']).tap do |payload|
                                                  payload['message']['id'] = '3EB0AAAA0002'
                                                end.to_json))
    worker.poll

    expect(inbox.messages.pluck(:source_id)).to contain_exactly('3EB0AAAA0001', '3EB0AAAA0002')
  end

  it 'parks an entry it cannot read instead of blocking the shard' do
    redis.xadd(stream, frame.merge('payload' => 'not json'))

    expect(worker.poll).to eq(0)

    expect(redis.llen("#{prefix}dlq:events")).to eq(1)
    # Acknowledged even though it failed: the shard has to keep moving.
    expect(redis.xpending(stream, described_class::Consumer::GROUP)['size']).to eq(0)
  end

  it 'retries a failure that a second attempt could fix' do
    stub_const("#{described_class}::RETRY_WAITS", [0, 0])
    attempts = 0
    allow(Whatsapp::Session::Inbound::Dispatcher).to receive(:dispatch).and_wrap_original do |original, *args|
      attempts += 1
      raise ActiveRecord::Deadlocked, 'deadlock detected' if attempts < 3

      original.call(*args)
    end
    redis.xadd(stream, frame)

    expect(worker.poll).to eq(1)

    expect(attempts).to eq(3)
    expect(inbox.messages.pluck(:source_id)).to eq(['3EB0AAAA0001'])
    expect(redis.llen("#{prefix}dlq:events")).to eq(0)
  end

  it 'parks a failure that outlives the retries' do
    stub_const("#{described_class}::RETRY_WAITS", [0])
    allow(Whatsapp::Session::Inbound::Dispatcher).to receive(:dispatch).and_raise(ActiveRecord::Deadlocked, 'deadlock detected')
    redis.xadd(stream, frame)

    expect(worker.poll).to eq(0)

    expect(Whatsapp::Session::Inbound::Dispatcher).to have_received(:dispatch).twice
    expect(redis.llen("#{prefix}dlq:events")).to eq(1)
  end

  it 'waits out the chat lock instead of spending the ordinary retry budget on it' do
    stub_const("#{described_class}::RETRY_WAITS", [])
    stub_const("#{described_class}::BUSY_WAITS", [0, 0])
    attempts = 0
    allow(Whatsapp::Session::Inbound::Dispatcher).to receive(:dispatch).and_wrap_original do |original, *args|
      attempts += 1
      raise Whatsapp::Session::Inbound::Locks::Busy, 'a group sync holds it' if attempts < 3

      original.call(*args)
    end
    redis.xadd(stream, frame)

    expect(worker.poll).to eq(1)

    expect(attempts).to eq(3)
    expect(inbox.messages.pluck(:source_id)).to eq(['3EB0AAAA0001'])
  end

  it 'leaves an entry pending when it is stopped mid-retry' do
    stub_const("#{described_class}::RETRY_WAITS", [0, 0])
    allow(Whatsapp::Session::Inbound::Dispatcher).to receive(:dispatch) do
      worker.stop
      raise ActiveRecord::Deadlocked, 'deadlock detected'
    end
    redis.xadd(stream, frame)

    expect(worker.poll).to eq(0)

    # Neither acknowledged nor dead-lettered: whoever takes the shard next claims it by
    # idle time and gets to try the event itself.
    expect(redis.xpending(stream, described_class::Consumer::GROUP)['size']).to eq(1)
    expect(redis.llen("#{prefix}dlq:events")).to eq(0)
  end

  # Every database call this thread makes has to sit inside the executor: it is a
  # long-lived thread outside the request cycle, and a connection checked out here is
  # only returned when the wrap closes.
  it 'runs each attempt inside the Rails executor' do
    stub_const("#{described_class}::RETRY_WAITS", [0])
    allow(Rails.application.executor).to receive(:wrap).and_call_original
    allow(Whatsapp::Session::Inbound::Dispatcher).to receive(:dispatch).and_raise(ActiveRecord::Deadlocked, 'deadlock detected')
    redis.xadd(stream, frame)

    worker.poll

    expect(Rails.application.executor).to have_received(:wrap).twice
  end

  # A lease can lapse while this thread is inside the shard: one long stall, or a Redis
  # that went away for half a minute. A peer takes the shard the moment it does, so the
  # only safe thing left is to touch nothing. The entry stays pending for whoever holds
  # the shard now, and this worker stops rather than reading on.
  it 'stops without dispatching once its lease is no longer fresh' do
    lease
    stub_const("#{Whatsapp::Connector::Consumer::ShardLease}::TTL", 0)
    redis.xadd(stream, frame)

    expect(worker.poll).to eq(0)

    expect(inbox.messages).to be_empty
    expect(redis.xpending(stream, described_class::Consumer::GROUP)['size']).to eq(1)
    expect(worker).to be_stopped
  end

  # Retrying here would re-run a handler that had already committed, turning a Redis
  # hiccup into a guaranteed duplicate rather than a possible one.
  it 'does not dispatch again when the cursor cannot be written' do
    lease # taken while Redis#set still works: the fence is not what this example is about
    allow_any_instance_of(Redis).to receive(:set).and_raise(Redis::TimeoutError, 'timed out') # rubocop:disable RSpec/AnyInstance
    redis.xadd(stream, frame)

    expect(worker.poll).to eq(1)

    expect(inbox.messages.pluck(:source_id)).to eq(['3EB0AAAA0001'])
    expect(redis.llen("#{prefix}dlq:events")).to eq(0)
  end

  # The job transport is Redis as well, and a different client from this worker's own:
  # Sidekiq goes through redis-client behind a pool, so a blip there arrives under names
  # the gem this worker uses never raises. Parking those would drop inbound events for
  # good every time Sidekiq's connections ran short.
  [ConnectionPool::TimeoutError, RedisClient::ConnectionError].each do |failure|
    it "leaves an entry pending when the job transport fails with #{failure}" do
      stub_const("#{described_class}::RETRY_WAITS", [0])
      stub_const("#{described_class}::STALL_WAIT", 0)
      allow(Whatsapp::Session::Inbound::Dispatcher).to receive(:dispatch).and_raise(failure, 'no connection')
      redis.xadd(stream, frame)

      expect(worker.poll).to eq(0)

      expect(redis.xpending(stream, described_class::Consumer::GROUP)['size']).to eq(1)
      expect(redis.llen("#{prefix}dlq:events")).to eq(0)
    end
  end

  # A failover longer than the retry ladder used to empty the stream into the dead letter
  # list and acknowledge every entry, so an ordinary database outage lost inbound messages
  # for good. The DLQ is capped and nothing replays it.
  it 'leaves an entry pending while the database is down rather than parking it' do
    stub_const("#{described_class}::RETRY_WAITS", [0])
    stub_const("#{described_class}::STALL_WAIT", 0)
    allow(Whatsapp::Session::Inbound::Dispatcher).to receive(:dispatch)
      .and_raise(ActiveRecord::ConnectionNotEstablished, 'no connection')
    redis.xadd(stream, frame)

    expect(worker.poll).to eq(0)

    expect(redis.llen("#{prefix}dlq:events")).to eq(0)
    expect(redis.xpending(stream, described_class::Consumer::GROUP)['size']).to eq(1)
  end

  # The shape a failover most often takes: the connection is dropped while a query is in
  # flight, which raises ConnectionFailed. It hangs off QueryAborted rather than off
  # ConnectionNotEstablished, so a list of leaf classes let exactly this one through.
  it 'treats a connection dropped mid-query as an outage too' do
    stub_const("#{described_class}::RETRY_WAITS", [0])
    stub_const("#{described_class}::STALL_WAIT", 0)
    allow(Whatsapp::Session::Inbound::Dispatcher).to receive(:dispatch)
      .and_raise(ActiveRecord::ConnectionFailed, 'the connection was closed')
    redis.xadd(stream, frame)

    expect(worker.poll).to eq(0)

    expect(redis.llen("#{prefix}dlq:events")).to eq(0)
    expect(redis.xpending(stream, described_class::Consumer::GROUP)['size']).to eq(1)
  end

  it 'stops working the batch once it is waiting on the database' do
    stub_const("#{described_class}::RETRY_WAITS", [])
    stub_const("#{described_class}::STALL_WAIT", 0)
    allow(Whatsapp::Session::Inbound::Dispatcher).to receive(:dispatch)
      .and_raise(ActiveRecord::ConnectionTimeoutError, 'could not obtain a connection')
    3.times { |n| redis.xadd(stream, frame.merge('id' => "evt-#{n}")) }

    worker.poll

    # One attempt, not one per entry: they all fail the same way and they are all still
    # there to try again.
    expect(Whatsapp::Session::Inbound::Dispatcher).to have_received(:dispatch).once
    expect(redis.xpending(stream, described_class::Consumer::GROUP)['size']).to eq(3)
  end

  # A shape this build cannot read is not going to become readable, and taking the whole
  # retry ladder to find that out stalls every session that shares the shard.
  it 'parks a frame whose nested payload is malformed, without retrying it' do
    stub_const("#{described_class}::RETRY_WAITS", [0, 0, 0])
    allow(Whatsapp::Session::Model::Event).to receive(:from_frame).and_call_original
    payload = JSON.parse(frame['payload'])
    payload['message']['content'] = { 'type' => 'media', 'kind' => 'image', 'ref' => { 'kind' => 'carrier_pigeon' } }
    redis.xadd(stream, frame.merge('payload' => payload.to_json))

    expect(worker.poll).to eq(0)

    # Once, not four times: the ladder would hold the shard for its whole length and then
    # park the entry anyway.
    expect(Whatsapp::Session::Model::Event).to have_received(:from_frame).once
    expect(redis.llen("#{prefix}dlq:events")).to eq(1)
    expect(redis.xpending(stream, described_class::Consumer::GROUP)['size']).to eq(0)
  end

  it 'takes over what a dead consumer left unacknowledged' do
    redis.xadd(stream, frame)
    redis.xgroup(:create, stream, described_class::Consumer::GROUP, '0', mkstream: true)
    redis.xreadgroup(described_class::Consumer::GROUP, 'consumer-dead', stream, '>')

    expect(worker.poll).to eq(1)

    expect(inbox.messages.pluck(:source_id)).to eq(['3EB0AAAA0001'])
  end

  # The lease is what makes a shard single-reader, so a pending entry belongs to an owner
  # that is already gone. Leaving it to age out lets the newer events go first, move the
  # cursor past it, and turn it into a message that is silently never delivered.
  it 'drains a backlog longer than one batch before it reads anything new' do
    stub_const("#{described_class}::BATCH", 2)
    ids = (1..5).map { |n| format('3EB0AAAA%<n>04d', n: n) }
    ids.each do |source_id|
      payload = JSON.parse(frame['payload'])
      payload['message']['id'] = source_id
      redis.xadd(stream, frame.merge('id' => "evt-#{source_id}", 'seq' => ids.index(source_id).succ.to_s,
                                     'payload' => payload.to_json))
    end
    redis.xgroup(:create, stream, described_class::Consumer::GROUP, '0', mkstream: true)
    redis.xreadgroup(described_class::Consumer::GROUP, 'consumer-dead', stream, '>', count: 5)

    expect(worker.poll).to eq(5)

    expect(inbox.messages.pluck(:source_id)).to match_array(ids)
    expect(redis.xpending(stream, described_class::Consumer::GROUP)['size']).to eq(0)
  end
end
